name: BINF7700
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12.1
  - numpy=2.3.5
  - pandas=2.3.3
  - genomekit=7.2.2
  - sh=2.2.2
  - jupyter=1.1.1
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - scipy=1.16.3
  - statsmodels=0.14.5
  - gseapy=1.1.11
  - adjusttext=1.3.0
